<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="rEvaluacion.aspx.cs" Inherits="PrimerParcial.Registros.rEvaluacion" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <%--Fecha--%>
     <div class="col-md-2 col-md-offset-8">
        <asp:Label Text="Fecha" runat="server"/>
            <asp:TextBox ID="FechaTextBox" class="form-control input-sm" TextMode="Date" runat="server"></asp:TextBox>
     </div>
    <%--EvaluacionID--%>
    <div class="col-md-2 col-md-offset-3">
        <asp:Label ID="EvaluacionIDLabel" runat="server" Text="ID"></asp:Label>
       <asp:TextBox ID="IDTextBox" class="form-control input-sm" TextMode="Number" runat="server" placeholder="0"></asp:TextBox>
        <asp:RequiredFieldValidator ID="RequiredFieldValidator" ValidationGroup="Buscar" ControlToValidate="IDTextBox" runat="server" ErrorMessage="*" ForeColor="Red" Display="Dynamic"></asp:RequiredFieldValidator>
    </div>
    <%--Buscar Button--%>
     <div class="col-md-2 col-sm-2 col-xs-2">
        <div class="input-group-append">
            <br />
                <asp:Button Text="Buscar" class="btn btn-primary" runat="server" ID="BuscarButton" OnClick="BuscarButton_Click1"/>
        </div>
     </div>
    <%--Estudiante--%>
    <div class="col-md-2 col-md-offset-3">
        <asp:Label ID="EstudianteLabel" runat="server" Text="Estudiante"></asp:Label>
        <asp:TextBox ID="EstudianteTextBox" runat="server"></asp:TextBox>
        <asp:RequiredFieldValidator ID="RequiredFieldValidator1" ValidationGroup="Buscar" ControlToValidate="EstudianteTextBox" runat="server" ErrorMessage="*" ForeColor="Red" Display="Dynamic"></asp:RequiredFieldValidator>
    </div>
    <%--Categoria--%>
    <div class="col-md-2 col-md-offset-3">
        <asp:Label ID="CategoriaLabel" runat="server" Text="Categoria"></asp:Label>
        <asp:TextBox ID="CategoriaTextBox" runat="server"></asp:TextBox>
        <asp:RequiredFieldValidator ID="RequiredFieldValidator2" ValidationGroup="Buscar" ControlToValidate="CategoriaTextBox" runat="server" ErrorMessage="*" ForeColor="Red" Display="Dynamic"></asp:RequiredFieldValidator>
    </div>
    <%--Valor--%>
    <div class="col-md-2 col-md-offset-3">
        <asp:Label ID="ValorLabel" runat="server" Text="Valor"></asp:Label>
        <asp:TextBox ID="ValorTextBox" runat="server"></asp:TextBox>
        <asp:RequiredFieldValidator ID="RequiredFieldValidator3" ValidationGroup="Buscar" ControlToValidate="ValorTextBox" runat="server" ErrorMessage="*" ForeColor="Red" Display="Dynamic"></asp:RequiredFieldValidator>
    </div>
    <%--Logrado--%>
    <div class="col-md-2 col-md-offset-3">
        <asp:Label ID="LogradoLabel" runat="server" Text="Valor"></asp:Label>
        <asp:TextBox ID="LogradoTextBox" runat="server"></asp:TextBox>
        <asp:RequiredFieldValidator ID="RequiredFieldValidator4" ValidationGroup="Buscar" ControlToValidate="LogradoTextBox" runat="server" ErrorMessage="*" ForeColor="Red" Display="Dynamic"></asp:RequiredFieldValidator>
    </div>

    <%--Grid--%>
       <asp:GridView ID="DetalleGridView" class="col-md-3 col-md-offset-3" runat="server" DataKeyNames="EvaluacionID" AllowPaging="true" PageSize="10" ShowHeaderWhenEmpty="false" AutoGenerateDeleteButton="true" CellPadding="4" ForeColor="#333333" OnRowDeleting="Grid_RowDeleting" GridLines="None" Width="767px" AutoGenerateColumns="false"   >
                    <Columns>

                        <asp:BoundField DataField="Categoria" HeaderText="Categoria" />
                        <asp:BoundField />
                        <asp:BoundField DataField="Valor" HeaderText="Valor" />
                        <asp:BoundField />
                        <asp:BoundField DataField="Perdido" HeaderText="Perdido" />
                        <asp:BoundField />
                    </Columns>
                    <EmptyDataTemplate>
                        <div style="text-align: center">Se han eliminado todas las filas</div>
                    </EmptyDataTemplate>
                    <AlternatingRowStyle BackColor="White" />

                    <EditRowStyle BackColor="#2461BF" />
                    <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#EFF3FB" />
                    <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#F5F7FB" />
                    <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                    <SortedDescendingCellStyle BackColor="#E9EBEF" />
                    <SortedDescendingHeaderStyle BackColor="#4870BE" />

                </asp:GridView>
    <%--Total--%>
    <div class="col-md-2 col-md-offset-3">
        <asp:Label ID="TotalLabel" runat="server" Text="Total Perdido"></asp:Label>
        <asp:TextBox ID="TotalTextBox" runat="server"></asp:TextBox>
        <asp:RequiredFieldValidator ID="RequiredFieldValidator5" ValidationGroup="Buscar" ControlToValidate="LogradoTextBox" runat="server" ErrorMessage="*" ForeColor="Red" Display="Dynamic"></asp:RequiredFieldValidator>
    </div>
    <div class="form-group">
                                <asp:Button ID="NuevoButton" runat="server" Text="Nuevo" class="btn btn-primary" />
                                <asp:Button ID="GuardarButton" runat="server" Text="Guardar" class="btn btn-success" ValidationGroup="Guardar" OnClick="GuardarButton_Click" />
                                <asp:Button ID="EliminarButton" runat="server" Text="Eliminar" class="btn btn-danger" OnClick="EliminarButton_Click" />
                            </div>
</asp:Content>
